### ISSUE TITLE
Uglifyjs fails to compile this module in create-react-app

### ISSUE THREAD

**Issue by WickyNilliams** [sindresorhus/p-pipe#2]
I'm not sure if this a problem with uglify, webpack's uglify plugin, babel, or something else (argh, tools).

In a fresh app create with `create-react-app` uglify chokes on this module.

Steps to reproduce:

```sh
yarn global add create-react-app
create-react-app uglify-test
cd uglify-test/
yarn add p-pipe
# ...import p-pipe in the project...
yarn build
```

It fails with the following error:

```
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

 	./node_modules/p-pipe/index.js:12
```

**Comment by WickyNilliams** [comment]
What's weird is this kind of error is usually due to ES6 code being published to npm, but the code here is strictly ES5.

**Comment by SamVerschueren** [comment]
We aim for Node.js, not the browser. You can find a more detailed explanation here https://github.com/sindresorhus/ama/issues/446.

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.

And no, it's not ES5. It has `const`, which is not an issue for Uglify, but the [fat arrow function](https://github.com/sindresorhus/p-pipe/blob/master/index.js#L12) is.

**Comment by WickyNilliams** [comment]
Ah yes, my bad, missed the `const` and the fat arrow. I totally understand the motivation, it's major hassle setting up build steps for so many modules.

That said, given the ES6 features used here are not crucial, and browser support could easily be had by swapping for ES5 equivalents, would you be open to a PR to do just that?

**Comment by SamVerschueren** [comment]
No sorry. It's explained in the AMA. There are multiple options to solve this. The suggestion I did is not the only valid option. There's also UglifyES for instance.

**Comment by WickyNilliams** [comment]
Fair enough. Though introducing new tooling is the least desirable of all options imo. I'll just copy and paste the lib into my project. Cheers

**Comment by SamVerschueren** [comment]
Introducing tooling for every single library is even less desirable. Its not up to maintainers to build their library for every single target out there. That's what Webpack should solve.
