### ISSUE TITLE
[TS] value is required

### ISSUE THREAD

**Issue by DTupalov** [sindresorhus/p-pipe#8]
Hi!
Is there any reasons to make [`value`](https://github.com/sindresorhus/p-pipe/blob/v3.0.0/index.d.ts#L3) required for p-pipe def?

I have scenario, when first function don't require any input data (fetching data), but next function handle result.

**Comment by sindresorhus** [comment]
No, I probably just didn't think of a use-case to allow. PR welcome to change it.

**Comment by yun-sangho** [comment]
May I take this issue?
